---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/cli
    tag: 'latest'

inputs:
- name: bosh-cli
  path: gopath/src/github.com/stuart-pollock/bosh-cli
- name: version-semver

outputs:
- name: compiled-windows

params:
  GOOS:   windows
  GOARCH: amd64
  CGO_ENABLED: 0
  FILENAME_PREFIX: ''

run:
  path: gopath/src/github.com/stuart-pollock/bosh-cli/ci/tasks/build.sh
