---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/cli
    tag: 'latest'

inputs:
- name: bosh-cli
  path: gopath/src/github.com/stuart-pollock/bosh-cli

run:
  path: gopath/src/github.com/stuart-pollock/bosh-cli/ci/tasks/test-unit.sh
