---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-garden
    tag: 'latest'

inputs:
- name: bosh-cli
  path: gopath/src/github.com/stuart-pollock/bosh-cli
- name: bosh-warden-cpi-release
  path: cpi-release

run:
  path: gopath/src/github.com/stuart-pollock/bosh-cli/ci/tasks/test-acceptance.sh
