---
platform: windows

inputs:
- name: bosh-cli
  path: gopath/src/github.com/stuart-pollock/bosh-cli

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - gopath/src/github.com/stuart-pollock/bosh-cli/ci/tasks/test-unit.ps1
